version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net
  mysql_db_container:
    image: mysql:latest
    container_name: mysqlDB
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3306:3306
    volumes:
      - mysql_db_data_container:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
  adminer_container:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db_container
    ports:
      - 8080:8080
  nmapdojo-report:
    depends_on:
      - rabbitmq
      - mysql_db_container
    image: nmapdojo-report
  nmapdojo-plaza:
    depends_on:
      - rabbitmq
      - mysql_db_container
    image: nmapdojo-plaza
    ports:
      - 8000:8000
volumes:
  mysql_db_data_container: 

networks:
  rabbitmq_go_net:
    driver: bridge